[project]
name = "decompiling-transformers"
version = "0.1.0"
description = "Implementation of 'Discovering Interpretable Algorithms by Decompiling Transformers to RASP'"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.1",
    "dacite>=1.9.2",
    "matplotlib>=3.10.8",
    "numpy==1.26.4",
    "streamlit>=1.54.0",
    "streamlit-autorefresh>=1.0.1",
    "scikit-learn>=1.8.0",
    "torch==2.11.0",
    "transformer-lens>=1.10.0",
    "transformers==4.45.1",
]

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
]
